// website/src/app/betting/selected-player.component.ts
import { Component,  Input, Output, EventEmitter, OnInit, OnDestroy } from "@angular/core";
import { ISelectedPlayer, IUser, emptyUser, ITeam, ITournament, emptyTeam, emptySelectedPlayer, IMatch, emptyTournament } from "../shared/model";
import { photo, photoType} from '../shared/photos';
import { matchHasStarted } from "../shared/utils" ;

@Component({
  selector: 'pm-selected-player',
  templateUrl: './selected-player.component.html',
  styleUrls: ['./selected-player.component.css']
})
export class SelectedPlayerComponent implements OnInit, OnDestroy {

  @Input() mode : string = "EDIT" // EDIT VIEW
  @Input() selectedPlayer : ISelectedPlayer = emptySelectedPlayer();
  @Input() filteredTeam : ITeam = emptyTeam();
  @Input() availableMultipliers : number = NaN;
  @Input() matches : IMatch[] = [];
  @Input() loggedInUser : IUser = emptyUser();
  @Input() tournament: ITournament = emptyTournament();

  displayAddMultiplierModal    : boolean = false;
  displayRemoveMultiplierModal : boolean = false;
  displayRemovePlayerModal     : boolean = false;

  photo : string = '';
  photoType : string = '';


  ngOnInit(): void {
    this.photo = photo(this.selectedPlayer.playerStats.player) ;
    this.photoType = photoType(this.selectedPlayer.playerStats.player) ;
  }
  
  ngOnDestroy(): void {
  }

  shouldDisplayPlayer( selectedPlayer : ISelectedPlayer ) {
    return  selectedPlayer.playerStats.player.playerId && (
                this.mode === 'EDIT' ||
                (this.mode === 'VIEW' && !!selectedPlayer.played) ||
                (this.mode === 'VIEW' && this.matchHasStarted(selectedPlayer)) ||
                (this.mode === 'VIEW' && this.teamIsOwnedByLoggedInUser() ) 
            );
  }

  teamIsOwnedByLoggedInUser(){
      return this.filteredTeam && this.filteredTeam.user && this.loggedInUser &&
            (this.filteredTeam.user.userId === this.loggedInUser.userId) ;
  }  

  shouldDisplayPendingSelection( selectedPlayer : ISelectedPlayer ) {
    return  !selectedPlayer.playerStats.player.playerId && 
            this.mode === 'EDIT' ;
  }

  shouldDisplayAvailableMultipliers(){
    return this.mode === 'EDIT' && this.availableMultipliers > 0;
  }

  shouldDisplayPendingResult( selectedPlayer : ISelectedPlayer ) {
    return  this.mode == 'VIEW' && !this.matchHasStarted(selectedPlayer)  && 
            !(this.loggedInUser && (this.filteredTeam.user.userId === this.loggedInUser.userId));
  }

  maximumMultipliersPerPlayer() : number {
    return 3;
  }

  onMultiplierAdded(message: any): void {
    this.selectedPlayer.playerMultiplier = this.selectedPlayer.playerMultiplier + 1;
    this.multiplierAdded.emit( message );
    this.modalClosed(null);
  }

  onMultiplierRemoved(message: any): void {
    this.selectedPlayer.playerMultiplier = this.selectedPlayer.playerMultiplier - 1;
    this.multiplierRemoved.emit( message );
    this.modalClosed(null);
  }

  matchHasStarted( player:ISelectedPlayer ) {
    let matchId = player.playerStats.matchId;
    return matchHasStarted(matchId, this.matches);
  }

  playerCanBeRemoved( player: ISelectedPlayer ){
    return this.mode === 'EDIT' && this.shouldDisplayPlayer(player) 
            && !this.matchHasStarted(player) 
            && (!player.pastPick||(player.pastPick && this.availableMultipliers>=1))
            && player.confirmed ;
  }

  playerCanNotBeRemoved( player: ISelectedPlayer ) {
    return (this.mode === 'EDIT') && this.shouldDisplayPlayer(player) &&
            ( 
                this.matchHasStarted(player) 
                || (!!player.pastPick && (this.availableMultipliers<=0) )
                || (!player.confirmed && !player.played)
            );
  }

  moveLeft( player: ISelectedPlayer ) {
    if( this.mode === 'EDIT' 
      && this.playerCanBeMoved(player)
      && !!this.playerToLeftOf(player) ) {
        this.playerMovedLeft.emit(player);
    }
  }

  moveRight( player: ISelectedPlayer ) {
    if( this.mode === 'EDIT' 
        && this.playerCanBeMoved(player) 
        && !!this.playerToRightOf(player) ) {
        this.playerMovedRight.emit(player);
    }
  }

  playerIsInLastPosition( player: ISelectedPlayer ) : boolean {
      return player && ( player.position === this.filteredTeam.selection.length || !this.playerToRightOf(player) );
  }

  playerIsInFirstPosition( player: ISelectedPlayer ) : boolean {
      return player && ( player.position === 1 || !this.playerToLeftOf(player) );
  }

  playerToLeftOf( player: ISelectedPlayer ){
      let i = player.position - 2;
      let ret = null;
      for(  ; i>=0; i = i - 1 ){
          let temp = this.filteredTeam.selection[i];
          if( this.playerCanBeMoved(temp) ){
              ret = temp;
              break;
          }
      }
      //console.log('playerToLeftOf -> '+player.playerStats.player.playerName+' is '+JSON.stringify(ret));
      return ret;
  }

  playerToRightOf( player: ISelectedPlayer ){
      let i = player.position;
      let ret = null;
      for(  ; i<this.filteredTeam.selection.length; i = i + 1 ){
          let temp = this.filteredTeam.selection[i];
          if( this.playerCanBeMoved(temp) ){
              ret = temp;
              break;
          }
      }
      //console.log('playerToRightOf -> '+player.playerStats.player.playerName+' is '+JSON.stringify(ret));
      return ret;
  }

  playerCanBeMoved( player: ISelectedPlayer ) : boolean {
      return !!player && !!player.playerStats 
          && !!player.playerStats.player && !!player.playerStats.player.playerId 
          && !player.played
          && player.confirmed;
  }

  getPosition( player: ISelectedPlayer ) : string {
    return player.position ? '' + player.position : '';
  }

  needsNextRoundSelection( player: ISelectedPlayer ) {
    return this.mode === 'EDIT' 
      && this.playerCanBeMoved( player)
      && ( this.currentRoundTeamSize() > this.nextRoundTeamSize() )
  }

  currentRoundTeamSize() : number {
      let round = this.filteredTeam.round;
      let aRound = this.tournament.rounds.find( (r) => r.roundId === round.roundId );
      return aRound? aRound.teamSize : 0;
  }

  nextRoundTeamSize() : number {
      let round = this.filteredTeam.round;
      if( this.tournament.finalRound === round.roundId ){
          return 1000;
      }
      let aRound = this.tournament.rounds.find( (r) => r.roundId === (round.roundId + 1) );
      return aRound? aRound.teamSize : 0;
  }

  playerIsConfirmed( player: ISelectedPlayer ) : boolean {
    return player.confirmed || player.played ;
  }

  modalClosed( player: any ) {
    this.displayAddMultiplierModal = false;
    this.displayRemoveMultiplierModal = false;
    this.displayRemovePlayerModal = false;
  }

  confirmMultiplierRemoved() {
    if( (this.selectedPlayer.playerMultiplier > 1) 
          && !this.selectedPlayer.played ){
        this.displayRemoveMultiplierModal = true;
    }
  }

  confirmMultiplierAdded() {
    if( (this.selectedPlayer.playerMultiplier < this.maximumMultipliersPerPlayer()) 
          && (this.availableMultipliers > 0) 
          && !this.selectedPlayer.played ){
        this.displayAddMultiplierModal = true;
    }
  }

  confirmPlayerRemoval(){
    this.displayRemovePlayerModal = true;
  }

  addMultiplierMessage(){
    return 'Agregar una pelotita multiplicadora a ' + this.selectedPlayer.playerStats.player.playerName +' ?'
  }

  removeMultiplierMessage(){
    return 'Quitar una pelotita multiplicadora a ' + this.selectedPlayer.playerStats.player.playerName +' ?'
  }

  removePlayerMessage(){
    return 'Quitar a ' + this.selectedPlayer.playerStats.player.playerName +' de mi equipo?';
  }

  penaltyMessage(){
    let msg = '';
    if( this.selectedPlayer.pastPick ){
        msg = msg + 'Esto consumirá una pelotita multiplicadora. '
    }
    return msg;
  }

  onPlayerRemoved( player : any ){
    this.playerRemoved.emit(player);
  }

  @Output() 
  multiplierAdded: EventEmitter<ISelectedPlayer> = new EventEmitter<ISelectedPlayer>();
  
  @Output() 
  multiplierRemoved: EventEmitter<ISelectedPlayer> = new EventEmitter<ISelectedPlayer>();

  @Output() 
  playerRemoved: EventEmitter<ISelectedPlayer> = new EventEmitter<ISelectedPlayer>();
  
  @Output() 
  playerMovedRight: EventEmitter<ISelectedPlayer> = new EventEmitter<ISelectedPlayer>();

  @Output() 
  playerMovedLeft: EventEmitter<ISelectedPlayer> = new EventEmitter<ISelectedPlayer>();
}

<div class="card h-100">
    <div class="card-header">
      <div class="row">
          <div class="col-md-1">
            <span class="pull-left" style="padding:3%">
              {{getPosition(selectedPlayer)}}
            </span>
          </div>
          <div class="col-md-3">&nbsp;</div>
          <div class="col-md-7" style="text-align:right">
            <ng-container *ngIf = 'playerCanBeRemoved(selectedPlayer)' >
                <span class="pull-right clickable close-icon playnice" data-effect="fadeOut" 
                          (click)='confirmPlayerRemoval()'>
                    <i class="fa fa-times"></i>
                </span>
            </ng-container>
            <ng-container *ngIf = 'playerCanNotBeRemoved(selectedPlayer)' >
              <span class="pull-right playnice" data-effect="fadeOut" >
                    <i class="fa fa-thumb-tack"></i> 
              </span>
            </ng-container> 
          </div>
      </div>
    </div>
    <div class="card-block">
        <div>
          <ng-container *ngIf = 'shouldDisplayPlayer(selectedPlayer)' >
              <div class="row center">
                  <div>
                      <div class='{{photoType}}' >
                        <a href="{{selectedPlayer.playerStats.player.playerProfileUrl}}"  target="_blank">
                          <img src="{{photo}}" style="width:100%" />
                        </a> 
                      </div> 
                      <div>                  
                        <a href="{{selectedPlayer.playerStats.player.playerProfileUrl}}"  target="_blank">
                          {{ selectedPlayer.playerStats.player.playerName }}
                        </a>
                      </div>
                      <ng-container *ngIf = 'playerIsConfirmed(selectedPlayer)' >
                        <div>Puntos en juego {{ selectedPlayer.playerStats.pointsToAward }}</div> 
                      </ng-container>
                      <ng-container *ngIf = '!playerIsConfirmed(selectedPlayer)' >
                        <div>&nbsp;</div>
                      </ng-container>
                  </div>
              </div>
          </ng-container>
          <ng-container *ngIf = 'shouldDisplayPendingSelection(selectedPlayer)'>
              <div class="hidden-player">
                <img src="assets/images/yellow-question-mark.png" >
              </div>
          </ng-container>
          <ng-container *ngIf = 'shouldDisplayPendingResult(selectedPlayer)'>
            <div class="hidden-player">
              <img src="assets/images/yellow-question-mark.png" >
            </div>
          </ng-container>
          <ng-container *ngIf = 'shouldDisplayPlayer(selectedPlayer)' >
              <div>
                <pm-multiplier 
                    [multiplier]='selectedPlayer.playerMultiplier' 
                    [mode]='mode' 
                    [player]='selectedPlayer'
                    [matches]="matches"
                    [maximumMultipliers]='maximumMultipliersPerPlayer()'
                    (multiplierAdded)='confirmMultiplierAdded()'
                    (multiplierRemoved)='confirmMultiplierRemoved()'>
                </pm-multiplier>
              </div>
          </ng-container>
          <ng-container *ngIf = 'shouldDisplayPlayer(selectedPlayer) && playerIsConfirmed(selectedPlayer)' >
              <div>
                  <ng-container *ngIf = '!!selectedPlayer.played'>Puntaje {{ selectedPlayer.playerScore }}</ng-container>
                  <ng-container *ngIf = '!selectedPlayer.played'>Resultado Pendiente</ng-container>
              </div>
          </ng-container>
          <ng-container *ngIf = 'shouldDisplayPlayer(selectedPlayer) && !playerIsConfirmed(selectedPlayer)' >
            <div>
                Esperando resultado de la ronda anterior
            </div>
          </ng-container>
          <ng-container *ngIf = 'needsNextRoundSelection(selectedPlayer)' >
              <div class="card" style="margin:3%;padding:2%;">
                <div class="row">                    
                    <div class="col-md-6">
                        <ng-container *ngIf = '!playerIsInFirstPosition(selectedPlayer)' >
                        <i class="fa fa-arrow-left" aria-hidden="true" (click)="moveLeft(selectedPlayer)"></i>
                        </ng-container>
                    </div>
                    <div class="col-md-6">
                      <ng-container *ngIf = '!playerIsInLastPosition(selectedPlayer)' >
                      <i class="fa fa-arrow-right" aria-hidden="true" (click)="moveRight(selectedPlayer)"></i>
                      </ng-container>
                  </div>
                </div>
              </div>
          </ng-container>
        </div> 
    </div>
</div>

<pm-player-modal 
        [player]="selectedPlayer" 
        [playerName]="selectedPlayer.playerStats.player.playerName"
        [playerProfilePic]="photo"         
        [message]="addMultiplierMessage()"
        [display]="displayAddMultiplierModal"
        (onModalAccepted)="onMultiplierAdded($event)"
        (onModalCancelled)="modalClosed($event)">
</pm-player-modal>

<pm-player-modal 
        [player]="selectedPlayer" 
        [playerName]="selectedPlayer.playerStats.player.playerName"
        [playerProfilePic]="photo" 
        [message]="removeMultiplierMessage()"
        [display]="displayRemoveMultiplierModal"
        (onModalAccepted)="onMultiplierRemoved($event)"
        (onModalCancelled)="modalClosed($event)">
</pm-player-modal>

<pm-player-modal 
        [player]="selectedPlayer" 
        [playerName]="selectedPlayer.playerStats.player.playerName"
        [playerProfilePic]="photo"  
        [message]="removePlayerMessage()"
        [warning]="penaltyMessage()"
        [display]="displayRemovePlayerModal"
        (onModalAccepted)="onPlayerRemoved($event)"
        (onModalCancelled)="modalClosed($event)">
</pm-player-modal>

// mobile/src/components/team/SelectedPlayer.tsx
import React from 'react';
import {
  Alert,
  Image,
  Linking,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { colors } from '@/theme';
import {
  ISelectedPlayer,
  ITeam,
  IUser,
  ITournament,
  IMatch,
} from '@/types/model';
import { photo, QUESTION_MARK } from '@/utils/photos';
import { matchHasStarted as matchStarted } from '@/utils/utils';
import { Multiplier } from './Multiplier';

const MAX_MULTIPLIERS_PER_PLAYER = 3;

interface Props {
  selectedPlayer: ISelectedPlayer;
  mode: 'VIEW' | 'EDIT';
  matches: IMatch[];
  filteredTeam: ITeam;
  loggedInUser: IUser;
  tournament: ITournament;
  availableMultipliers: number;
  onPlayerRemoved: (p: ISelectedPlayer) => void;
  onMultiplierAdded: (p: ISelectedPlayer) => void;
  onMultiplierRemoved: (p: ISelectedPlayer) => void;
  onMoveLeft: (p: ISelectedPlayer) => void;
  onMoveRight: (p: ISelectedPlayer) => void;
}

export function SelectedPlayer(props: Props) {
  const {
    selectedPlayer: sp,
    mode,
    matches,
    filteredTeam,
    loggedInUser,
    tournament,
    availableMultipliers,
  } = props;

  const player = sp.playerStats.player;

  const teamIsOwnedByLoggedInUser = () =>
    !!filteredTeam?.user && !!loggedInUser && filteredTeam.user.userId === loggedInUser.userId;

  const matchHasStarted = () => matchStarted(sp.playerStats.matchId, matches);

  const shouldDisplayPlayer = () =>
    !!player.playerId &&
    (mode === 'EDIT' ||
      (mode === 'VIEW' && !!sp.played) ||
      (mode === 'VIEW' && matchHasStarted()) ||
      (mode === 'VIEW' && teamIsOwnedByLoggedInUser()));

  const playerIsConfirmed = () => sp.confirmed || sp.played;

  const playerCanBeMoved = (p?: ISelectedPlayer) =>
    !!p && !!p.playerStats?.player?.playerId && !p.played && p.confirmed;

  const playerToLeftOf = (p: ISelectedPlayer) => {
    for (let i = p.position - 2; i >= 0; i--) {
      if (playerCanBeMoved(filteredTeam.selection[i])) return filteredTeam.selection[i];
    }
    return null;
  };
  const playerToRightOf = (p: ISelectedPlayer) => {
    for (let i = p.position; i < filteredTeam.selection.length; i++) {
      if (playerCanBeMoved(filteredTeam.selection[i])) return filteredTeam.selection[i];
    }
    return null;
  };

  const currentRoundTeamSize = () => {
    const round = filteredTeam.round;
    const r = tournament.rounds.find((x) => x.roundId === round.roundId);
    return r ? r.teamSize : 0;
  };
  const nextRoundTeamSize = () => {
    const round = filteredTeam.round;
    if (tournament.finalRound === round.roundId) return 1000;
    const r = tournament.rounds.find((x) => x.roundId === round.roundId + 1);
    return r ? r.teamSize : 0;
  };

  const needsNextRoundSelection = () =>
    mode === 'EDIT' && playerCanBeMoved(sp) && currentRoundTeamSize() > nextRoundTeamSize();

  const playerCanBeRemoved = () =>
    mode === 'EDIT' &&
    shouldDisplayPlayer() &&
    !matchHasStarted() &&
    (!sp.pastPick || (sp.pastPick && availableMultipliers >= 1)) &&
    sp.confirmed;

  const playerCanNotBeRemoved = () =>
    mode === 'EDIT' &&
    shouldDisplayPlayer() &&
    (matchHasStarted() ||
      (!!sp.pastPick && availableMultipliers <= 0) ||
      (!sp.confirmed && !sp.played));

  const confirmRemove = () => {
    let warning = '';
    if (sp.pastPick) warning = 'Esto consumirá una pelotita multiplicadora. ';
    Alert.alert('Quitar jugador', `${warning}Quitar a ${player.playerName} de mi equipo?`, [
      { text: 'Cancelar', style: 'cancel' },
      { text: 'Aceptar', onPress: () => props.onPlayerRemoved(sp) },
    ]);
  };

  const confirmAddMultiplier = () => {
    if (sp.playerMultiplier < MAX_MULTIPLIERS_PER_PLAYER && availableMultipliers > 0 && !sp.played) {
      Alert.alert(
        'Multiplicador',
        `Agregar una pelotita multiplicadora a ${player.playerName}?`,
        [
          { text: 'Cancelar', style: 'cancel' },
          { text: 'Aceptar', onPress: () => props.onMultiplierAdded(sp) },
        ],
      );
    }
  };

  const confirmRemoveMultiplier = () => {
    if (sp.playerMultiplier > 1 && !sp.played) {
      Alert.alert(
        'Multiplicador',
        `Quitar una pelotita multiplicadora a ${player.playerName}?`,
        [
          { text: 'Cancelar', style: 'cancel' },
          { text: 'Aceptar', onPress: () => props.onMultiplierRemoved(sp) },
        ],
      );
    }
  };

  const openProfile = () => {
    if (player.playerProfileUrl) Linking.openURL(player.playerProfileUrl);
  };

  const showPlayer = shouldDisplayPlayer();
  const canRemove = playerCanBeRemoved();
  const canNotRemove = playerCanNotBeRemoved();

  return (
    <View style={styles.card}>
      <View style={styles.header}>
        <Text style={styles.position}>{sp.position ? sp.position : ''}</Text>
        {canRemove && (
          <TouchableOpacity onPress={confirmRemove}>
            <Text style={styles.removeIcon}>✕</Text>
          </TouchableOpacity>
        )}
        {canNotRemove && <Text style={styles.pinIcon}>📌</Text>}
      </View>

      <View style={styles.body}>
        {showPlayer ? (
          <>
            <TouchableOpacity onPress={openProfile} style={styles.center}>
              <Image source={photo(player)} style={styles.photo} resizeMode="cover" />
              <Text style={styles.name}>{player.playerName}</Text>
            </TouchableOpacity>
            {playerIsConfirmed() ? (
              <Text style={styles.points}>Puntos en juego {sp.playerStats.pointsToAward}</Text>
            ) : null}

            <Multiplier
              multiplier={sp.playerMultiplier}
              maximumMultipliers={MAX_MULTIPLIERS_PER_PLAYER}
              mode={mode}
              disabled={matchHasStarted()}
              onAdd={confirmAddMultiplier}
              onRemove={confirmRemoveMultiplier}
            />

            {playerIsConfirmed() ? (
              sp.played ? (
                sp.playerScore > 0 ? (
                  <View style={styles.winner}>
                    <Text style={styles.winnerText}>Puntaje {sp.playerScore}</Text>
                  </View>
                ) : (
                  <Text style={styles.lost}>✕</Text>
                )
              ) : (
                <Text style={styles.pending}>Resultado Pendiente</Text>
              )
            ) : (
              <Text style={styles.pending}>Esperando resultado de la ronda anterior</Text>
            )}

            {needsNextRoundSelection() && (
              <View style={styles.moveRow}>
                {playerToLeftOf(sp) ? (
                  <TouchableOpacity onPress={() => props.onMoveLeft(sp)}>
                    <Text style={styles.arrow}>◀</Text>
                  </TouchableOpacity>
                ) : (
                  <View style={styles.arrowSpacer} />
                )}
                {playerToRightOf(sp) ? (
                  <TouchableOpacity onPress={() => props.onMoveRight(sp)}>
                    <Text style={styles.arrow}>▶</Text>
                  </TouchableOpacity>
                ) : (
                  <View style={styles.arrowSpacer} />
                )}
              </View>
            )}
          </>
        ) : (
          <View style={styles.center}>
            <Image source={QUESTION_MARK} style={styles.question} resizeMode="contain" />
          </View>
        )}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: '#fff',
    overflow: 'hidden',
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: colors.cardHeaderBg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    minHeight: 28,
  },
  position: { fontWeight: '700', color: colors.text },
  removeIcon: { color: colors.danger, fontWeight: '700', fontSize: 16 },
  pinIcon: { fontSize: 14 },
  body: { padding: 8, alignItems: 'center' },
  center: { alignItems: 'center' },
  photo: { width: 90, height: 66, borderRadius: 4 },
  name: {
    marginTop: 4,
    fontWeight: '600',
    color: colors.link,
    textAlign: 'center',
    fontSize: 13,
  },
  points: { fontSize: 12, color: colors.muted, marginTop: 2, textAlign: 'center' },
  winner: {
    backgroundColor: colors.winner,
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 4,
  },
  winnerText: { color: colors.primary, fontWeight: '700' },
  lost: { color: colors.danger, fontSize: 18, fontWeight: '700', marginTop: 4 },
  pending: { fontSize: 12, color: colors.muted, marginTop: 4, textAlign: 'center' },
  question: { width: 70, height: 70, marginVertical: 8 },
  moveRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 8,
    paddingHorizontal: 12,
  },
  arrow: { fontSize: 20, color: colors.primary },
  arrowSpacer: { width: 20 },
});
