// mobile/src/components/team/AvailablePlayer.tsx
import React from 'react';
import {
  Alert,
  Image,
  Linking,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { colors } from '@/theme';
import {
  IMatch,
  IMatchPlayer,
  IPlayer,
  ISelectedPlayer,
  ITeam,
  ITournament,
} from '@/types/model';
import { photo, QUESTION_MARK } from '@/utils/photos';
import { matchHasStarted } from '@/utils/utils';

interface Props {
  match: IMatch;
  player: IMatchPlayer;
  tournament: ITournament;
  team: ITeam;
  matches: IMatch[];
  onAdd: (p: ISelectedPlayer) => void;
}

export function AvailablePlayer({ match, player, tournament, team, matches, onAdd }: Props) {
  const playerExists = () => !!player.player && !!player.player.playerId;
  const playerHasRival = () => !!player.player && player.pointsToAward > 0;

  const teamContainsPlayer = (p: IPlayer) =>
    !!team?.selection?.find((e) => e.playerStats?.player?.playerId === p.playerId);

  const leagueQuotaFull = (p: IPlayer) => {
    if (!tournament?.activeLeagues) return false;
    const numActiveLeagues = tournament.activeLeagues;
    if (!(p && p.league && p.league.leagueId >= 0) || !team?.selection) return false;
    const quota = team.selection.length / numActiveLeagues;
    const selectedPlayers = team.selection.filter((e) => e.playerStats.player);
    const leaguePlayers = selectedPlayers.filter(
      (e) => e.playerStats?.player?.league?.leagueId === p.league.leagueId,
    );
    return leaguePlayers.length >= quota;
  };

  const shouldAllowAddition = () =>
    !teamContainsPlayer(player.player) &&
    !leagueQuotaFull(player.player) &&
    !matchHasStarted(match.matchId, matches) &&
    playerHasRival();

  const openProfile = () => {
    if (player.player.playerProfileUrl) Linking.openURL(player.player.playerProfileUrl);
  };

  const add = () => {
    Alert.alert('Agregar jugador', `Agregar a ${player.player.playerName} a mi equipo?`, [
      { text: 'Cancelar', style: 'cancel' },
      {
        text: 'Aceptar',
        onPress: () => {
          const selected: ISelectedPlayer = {
            position: 0,
            playerStats: {
              player: player.player,
              pointsToAward: player.pointsToAward,
              matchId: match.matchId,
            },
            playerMultiplier: 1,
            playerScore: 0,
            played: false,
            pastPick: false,
            confirmed: true,
          };
          onAdd(selected);
        },
      },
    ]);
  };

  if (!playerExists()) {
    return (
      <View style={styles.cell}>
        <Image source={QUESTION_MARK} style={styles.question} resizeMode="contain" />
      </View>
    );
  }

  const canAdd = shouldAllowAddition();

  return (
    <View style={styles.cell}>
      <Image source={photo(player.player)} style={styles.photo} resizeMode="cover" />
      <TouchableOpacity onPress={openProfile}>
        <Text style={styles.name}>{player.player.playerName}</Text>
      </TouchableOpacity>
      {playerHasRival() ? (
        <Text style={styles.points}>Puntos en juego {player.pointsToAward}</Text>
      ) : null}
      {canAdd ? (
        <TouchableOpacity style={styles.addBtn} onPress={add}>
          <Text style={styles.addBtnText}>＋</Text>
        </TouchableOpacity>
      ) : (
        <View style={styles.addSpacer} />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  cell: {
    flex: 1,
    alignItems: 'center',
    padding: 6,
  },
  photo: { width: 90, height: 66, borderRadius: 4 },
  name: {
    marginTop: 4,
    color: colors.link,
    fontWeight: '600',
    textAlign: 'center',
    fontSize: 13,
  },
  points: { fontSize: 12, color: colors.muted, marginTop: 2, textAlign: 'center' },
  question: { width: 60, height: 60, marginVertical: 8 },
  addBtn: {
    marginTop: 6,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtnText: { color: '#fff', fontSize: 20, fontWeight: '700', lineHeight: 22 },
  addSpacer: { height: 38 },
});

// website/src/app/betting/available-player.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from "@angular/core";
import { IPlayerStatsPerRound, ISelectedPlayer, emptyMatchPlayer, emptyMatch, IPlayer, ITeam, emptyTeam, IMatch, IMatchPlayer, ITournament, emptyTournament } from "../shared/model";
import { photo, photoType} from '../shared/photos';
import { matchHasStarted } from "../shared/utils" ;


@Component({ 
  selector: 'pm-available-player', 
  templateUrl: './available-player.component.html',
  styleUrls: ['./available-player.component.css']
})
export class AvailablePlayerComponent implements OnInit, OnDestroy {

  @Input() 
  player : IMatchPlayer = emptyMatchPlayer() ;
  
  @Input() 
  match : IMatch = emptyMatch() ;

  @Input()
  tournament : ITournament = emptyTournament();

  @Input() 
  team : ITeam = emptyTeam() ;  

  @Input() 
  matches : IMatch[] = [] ;  

  displayModal : boolean = false; 
  photo : string = '';
  photoType : string = '';

  ngOnInit(): void {
    this.photo = photo(this.player.player) ;
    this.photoType = photoType(this.player.player) ;
  }
  
  ngOnDestroy(): void {
  }

  teamContainsPlayer( player : IPlayer ){
    return (player && this.team && this.team.selection)?  
            this.team.selection.find( elem => 
              (elem.playerStats && elem.playerStats.player)? 
              elem.playerStats.player.playerId === player.playerId : false ) : false ;
  }

  leagueQuotaFull( player : IPlayer ){
    let result = false;
    if( this.tournament && this.tournament.activeLeagues ){
      let numActiveLeagues = this.tournament.activeLeagues;
      if( ( player.league.leagueId >= 0) && this.team && this.team.selection ){
          let quota = this.team.selection.length / numActiveLeagues ;
          let selectedPlayers = this.team.selection.filter( elem => elem.playerStats.player ); 
          if( selectedPlayers ){
            let leaguePlayers = selectedPlayers.filter( elem => 
                          ( elem && elem.playerStats && elem.playerStats.player && elem.playerStats.player.league )?
                          elem.playerStats.player.league.leagueId === player.league.leagueId : false ) ;
            result = ( leaguePlayers.length >= quota );
          }
      }
    }
    return result;
  }

  shouldAllowPlayerAddition( match : IMatch, player : IMatchPlayer ){
    return ! this.teamContainsPlayer( player.player )
            && ! this.leagueQuotaFull( player.player )
            && !matchHasStarted( match.matchId, this.matches )
            && this.playerHasRival( match, player );
  }

  playerExists( match :IMatch, player : IMatchPlayer ){
     return player.player && player.player.playerId ; 
  }

  playerHasRival( match :IMatch, player : IMatchPlayer ) : boolean {
    return !!player.player && player.pointsToAward > 0 ; 
  }

  onPlayerSelected( player : IMatchPlayer ){
    //console.log('onPlayerSelected -> '+this.match.matchId);
    let playerStats : IPlayerStatsPerRound = {
      player : player.player,
      pointsToAward: player.pointsToAward,  
      matchId: this.match.matchId
    };
    let selectedPlayer : ISelectedPlayer = {
      position : 0,
      playerStats : playerStats,
      playerMultiplier: 1,
      playerScore: 0,
      played: false,
      pastPick: false,
      confirmed: true
    };
    this.playerClicked.emit( selectedPlayer );
    this.modalClosed( player );
  }

  modalClosed( player : IMatchPlayer ){
    this.displayModal = false;
  }

  confirmSelection() {
    this.displayModal = true;
  }

  modalMessage() {
    return "Agregar a "+this.player.player.playerName+" a mi equipo?";
  }
  
  @Output() 
  playerClicked: EventEmitter<ISelectedPlayer> = new EventEmitter<ISelectedPlayer>();

}

<div class="card">
    <table class="table">
        <ng-container *ngIf = 'playerExists(match,player)'>
            <tr><td><img src="{{photo}}" style="width:100%"/></td></tr>
            <tr>
                <td>
                    <a href="{{player.player.playerProfileUrl}}" target="_blank">{{ player.player.playerName }}</a>
                </td>
            </tr>
            <ng-container *ngIf = 'playerHasRival(match,player)'>
                <tr><td>Puntos en juego {{ player.pointsToAward }}</td></tr>
            </ng-container>
            <ng-container *ngIf = 'shouldAllowPlayerAddition(match,player)'>
                <tr><td><img src="assets/images/plus-sign.svg" style="width:25%"
                    (click)="confirmSelection()"/></td></tr>   
            </ng-container>  
            <ng-container *ngIf = '!shouldAllowPlayerAddition(match,player)'>
                <tr><td><img src="assets/images/nothing.svg" style="width:25%"/></td></tr>   
            </ng-container>  
        </ng-container>
        <ng-container *ngIf = '!playerExists(match,player)'>
            <tr><td>
                <div class="hidden-player" >
                    <img src="assets/images/yellow-question-mark.png" style="width:83%">
                </div>
            </td></tr>   
            <ng-container *ngIf = '!shouldAllowPlayerAddition(match,player)'>
                <tr><td><img src="assets/images/nothing.svg" style="width:28%"/></td></tr>   
            </ng-container>  
        </ng-container>
    </table>   
</div>

<pm-player-modal 
        [player]="player" 
        [playerName]="player.player.playerName"
        [playerProfilePic]="photo" 
        [message]="modalMessage()"
        [display]="displayModal"
        (onModalAccepted)="onPlayerSelected($event)"
        (onModalCancelled)="modalClosed($event)">
</pm-player-modal>
